AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Create template version for student project
Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
         CidrBlock: 10.0.0.0./24
         InstanceTendency: default
         Tags:
            - Key: Name
              Value: studentProj-VPC
            - Key: Project
              Value: studentapp
